version: "3.5"
services:
  temporalite:
    container_name: temporalite
    image: tsurdilo/temporalite:latest
    ports:
      - 7233:7233
      - 8233:8233
    stdin_open: true
    tty: true
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporalite
    environment:
      - TEMPORAL_CLI_ADDRESS=temporalite:7233
    image: temporalio/admin-tools:1.17.5
    stdin_open: true
    tty: true
    healthcheck:
      test:
        [
            "CMD",
            "tctl",
            "--address",
            "temporalite:7233",
            "workflow",
            "list"
        ]
      interval: 1s
      timeout: 5s
      retries: 30
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporalite
    environment:
      - TEMPORAL_ADDRESS=temporalite:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
      - TEMPORAL_UI_PORT=8081
    image: temporalio/ui:2.5.0
    ports:
      - 8081:8081
networks:
  default:
    external: true
    name: temporal-network

