version: "3.5"
services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
    ports:
      - 5432:5432
  postgres-exporter:
    container_name: postgres-exporter
    image: wrouesnel/postgres_exporter:v0.8.0
    environment:
      - DATA_SOURCE_URI=postgresql:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=temporal
      - DATA_SOURCE_PASS=temporal
      - PG_EXPORTER_INCLUDE_DATABASES=temporal,temporal_visibility
    ports:
      - "9187:9187"
    depends_on:
      - postgresql
networks:
  default:
    external: true
    name: temporal-network