global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "temporalmetrics"
    metrics_path: /metrics
    scheme: http
    static_configs:
      # Server metrics target
      - targets:
          - "temporal-history:8000"
          - "temporal-matching:8001"
          - "temporal-frontend:8002"
          - "temporal-worker:8003"
          # - 'host.docker.internal:8004'
          # - "host.docker.internal:8005"
          # - "host.docker.internal:8006"
          - "temporal-internal-frontend:8007"
        labels:
          group: "server-metrics"

      # Local app targets (if configured)
      - targets:
          - "host.docker.internal:8077"
          - "host.docker.internal:8078"
        labels:
          group: "sdk-metrics"
      # Docker metrics
      - targets:
          - "host.docker.internal:9323"
        labels:
          group: "docker-metrics"
      # # Postgres Exporter
      # - targets:
      # - "host.docker.internal:9187"
      # labels:
      # group: "postgres-metrics"
      # # HAProxy Metrics
      # - targets:
      # - "host.docker.internal:8404"
      # labels:
      # group: "haproxy-metrics"
      # # Envoy Metrics
      # - targets:
      # - "host.docker.internal:9901"
      # labels:
      # group: "envoy-metrics"
    # this show how to drop certain metrics, for example here all metrics for temporal_system namespace
    metric_relabel_configs:
      - source_labels: [namespace]
        regex: "temporal_system"
        action: drop
  # - job_name: "springbootjavasdk"
  # metrics_path: /actuator/prometheus
  # scheme: http
  # static_configs:
  # - targets:
  # - "host.docker.internal:3030"
  # - "host.docker.internal:19994"
  # - "host.docker.internal:19995"
  # - "host.docker.internal:19996"
  # - "host.docker.internal:19997"
  # - "host.docker.internal:19998"
  # - "host.docker.internal:19999"
  # labels:
  # group: "spring-boot-metrics"

remote_write:
  - url: "<Your Prometheus remote_write endpoint>"
    basic_auth:
      username: "<Your Grafana Username>"
      password: "<Your Grafana API key>"
